### ISSUE TITLE
Uncaught TypeError in reTesselateCoplanarPolygons

### ISSUE THREAD

**Issue by kirevdokimov** [jscad/OpenJSCAD.org#1360]
I use **.union()** to merge geometries, but when I do so, it causes errors.

## Expected Behavior
Geometries are merged with no issues

## Actual Behavior
**.union()** throws an exception
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at reTesselateCoplanarPolygons (reTesselateCoplanarPolygons.js:176:40)
    at retessellate.js:25:44
    at Array.forEach (<anonymous>)
    at retessellate (retessellate.js:23:14)
    at union8 (unionGeom3.js:21:17)
    at union8 (union.js:42:35)
 ```

## Steps to Reproduce the Problem

I assume this basic example works for everyone
```
const c1 = cylinder({ radius: 3, height: 12, center: [0, 0, 5], segments: 12 })
const c2 = cylinder({ radius: 3, height: 18, center: [0, 0, 5], segments: 12 })

const u = union(c1, c2)
```

## Specifications

  - Version:  "@jscad/core": "^2.6.9", "@jscad/modeling": "^2.12.2",
  - Platform: Windows 11, Brave Browser,
  - Environment: Node v16.15.1, esbuild, Brave Browser Version 1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit)
  
  Same issue for Google Chrome Version 127.0.6533.122 (Official Build) (64-bit)

**Comment by kirevdokimov** [comment]
polygonindexKey is equal to "clear" or "remove" while we iterate over `startingpolygonindexes`, what causes `vertices2d` to be undefined.
![image](https://github.com/user-attachments/assets/a2fe1d5b-d5a6-4a07-9fea-6a6d58cb8111)
![image](https://github.com/user-attachments/assets/429a78c0-9d82-465e-a93c-b9360edcbf99)

If we check for Nan with `if (isNaN(polygonindexKey)) continue` line, other issue occurs:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '1')
    at interpolateBetween2DPointsForY (interpolateBetween2DPointsForY.js:11:16)
    at reTesselateCoplanarPolygons (reTesselateCoplanarPolygons.js:226:15)
    at retessellate.js:25:44
    at Array.forEach (<anonymous>)
    at retessellate (retessellate.js:23:14)
    at union8 (unionGeom3.js:21:17)
    at union8 (union.js:42:35)
```

**Comment by z3dev** [comment]
@kirevdokimov thanks for the excellent example, and the in-depth analysis.

there are lots of tests but not for this specific example. Given the similarity of the two cylinders, there's obviously something about the retellsation. Have you taken a look at the results of the Union before the retessellation? (Sorry for the spelling)

I'll look over the fix.

**Comment by kirevdokimov** [comment]
Responded in a related merge request: #1361

**Comment by platypii** [comment]
I was not able to reproduce this issue with the example you gave. Maybe I'm missing something?

![retess](https://github.com/user-attachments/assets/a8d813fe-434e-4054-9728-54b54f2bcd62)
