### ISSUE TITLE
Import stl in OPENSCAD translation failing

### ISSUE THREAD

**Issue by jessp** [jscad/OpenJSCAD.org#296]
I'm encountering an issue when trying to import stl files in an openSCAD file. 

In my .scad, I have the command:

`import("myObject.stl");`

or 

`import("myObject.stl", convexity = 4);`

and I receive the following error:

```
/usr/local/lib/node_modules/@jscad/openjscad/node_modules/@jscad/openscad-openjscad-translator/src/OpenjscadSolidFactory.js:63
      return new ImportModule(this)
             ^

TypeError: ImportModule is not a constructor
    at OpenjscadSolidFactory.getAdaptor (/usr/local/lib/node_modules/@jscad/openjscad/node_modules/@jscad/openscad-openjscad-translator/src/OpenjscadSolidFactory.js:63:14)
    at Context.evaluateModule (/usr/local/lib/node_modules/@jscad/openjscad/node_modules/@jscad/openscad-openjscad-translator/src/Context.js:87:29)
    at ModuleInstantiation.evaluate (/usr/local/lib/node_modules/@jscad/openjscad/node_modules/@jscad/openscad-openjscad-translator/src/ModuleInstantiation.js:31:29)
    at /usr/local/lib/node_modules/@jscad/openjscad/node_modules/@jscad/openscad-openjscad-translator/src/Module.js:53:34
    at arrayEach (/usr/local/lib/node_modules/@jscad/openjscad/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/usr/local/lib/node_modules/@jscad/openjscad/node_modules/lodash/lodash.js:9359:14)
    at Module.evaluate (/usr/local/lib/node_modules/@jscad/openjscad/node_modules/@jscad/openscad-openjscad-translator/src/Module.js:52:5)
    at Object.processModule (/usr/local/lib/node_modules/@jscad/openjscad/node_modules/@jscad/openscad-openjscad-translator/src/openscad-parser-ext.js:32:26)
    at Object.anonymous (/usr/local/lib/node_modules/@jscad/openjscad/node_modules/@jscad/openscad-openjscad-translator/src/parserCJS.js:94:24)
    at Parser.parse (/usr/local/lib/node_modules/@jscad/openjscad/node_modules/@jscad/openscad-openjscad-translator/src/parserCJS.js:641:36)
```

I know in the documentation it states that .dxf import into openscad files is still in progress, which suggests (to me) that .stl import should work? I've also looked at #8 and linked issues, but it's not 100% clear to me what the status on that front is and what the implications are.

Any thoughts would be appreciated. Thanks for all your hard work on this project!

**Comment by kaosat-dev** [comment]
Hello @jessp : there currently is NO support for importing stl files in that manner : you can only convert an stl to a jscad output and use that one.
We are however working on adding support (sooner rather than later):

https://github.com/jscad/io/issues/8
and 
https://github.com/jscad/io/issues/3 (more up to date information)

The syntax will however be different from the one in openscad, as ```import``` is a reserved word in Javascript (see the issue above for the likely syntax)

**Comment by jessp** [comment]
Understood
