### ISSUE TITLE
V1 : node cli.js "d:\1.dxf" error

### ISSUE THREAD

**Issue by gergul** [jscad/OpenJSCAD.org#526]
## Actual Behavior
`D:\Programming\OpenJSCAD.org\packages\cli>node cli.js "d:\1.dxf"
converting d:\1.dxf -> d:\1.stl (STereoLithography, ASCII)
TypeError: cag._toCSGWall is not a function
    at D:\Programming\OpenJSCAD.org\packages\core\node_modules\@jscad\csg\src\core\CAG.js:44:26
    at Array.map (<anonymous>)
    at CAG.union (D:\Programming\OpenJSCAD.org\packages\core\node_modules\@jscad\csg\src\core\CAG.js:43:18)
    at mergeSolids2 (D:\Programming\OpenJSCAD.org\packages\core\utils\mergeSolids.js:71:21)
    at prepareOutput (D:\Programming\OpenJSCAD.org\packages\core\io\prepareOutput.js:20:14)
    at D:\Programming\OpenJSCAD.org\packages\cli\generateOutputData.js:116:28
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
`

## Steps to Reproduce the Problem

  1.Download OpenJSCAD.org
  2.cd OpenJSCAD.org
  3.npm install 
  4.npm run bootstrap
  5.cd packages/cli
  6.node cli.js "d:\1.dxf"

## Specifications

  - Version:Lasted
  - Platform:windows10 x64
  - Environment: (browser, local server, node.js etc) node.js10.16.0

**Comment by z3dev** [comment]
@gergul Does the DXF contain valid geometry?

**Comment by gergul** [comment]
> @gergul Does the DXF contain valid geometry?

Thanks for your answer.The dxf contain a polyline,a circel,a text.no other.

[1.zip](https://github.com/jscad/OpenJSCAD.org/files/4255286/1.zip)

**Comment by z3dev** [comment]
V1 doesn't translated LINE entities correctlly.

**Comment by z3dev** [comment]
@gergul this bug is fixed in V2.

if you're still interested in using JSCAD then you might want to try V2. we are now asking for early adopters to participate.

https://openjscad.org/dokuwiki/doku.php?id=early_v2

**Comment by gergul** [comment]
thank you. I will try it.
