### ISSUE TITLE
V2 : Cannot find module 'most' (npm run dev in 'packages/web')

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#528]
## Expected Behavior
Web running without errors

## Actual Behavior

> @jscad/web@1.10.0 dev /opt/OpenJSCAD.org/packages/web
> budo demo.js --port=8081 --css demo.css --live -- -b

[0000] info  Server running at http://136.243.90.99:8081/ (connect)
[0000] info  LiveReload running
Error: **Cannot find module 'most'** from '/opt/OpenJSCAD.org/packages/web/src/sideEffects/state'
    at /opt/OpenJSCAD.org/packages/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/opt/OpenJSCAD.org/packages/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/opt/OpenJSCAD.org/packages/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/opt/OpenJSCAD.org/packages/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/opt/OpenJSCAD.org/packages/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /opt/OpenJSCAD.org/packages/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (fs.js:166:21) {
  stream: [Labeled]
}

## Steps to Reproduce the Problem

  1. follow eyrly adopter document https://openjscad.org/dokuwiki/doku.php?id=early_v2
  2. run the web: `npm run dev` in packages/web
  3.

## Specifications

  - Version: V2
  - Platform: Debian, and Windows
  - Environment: (browser, local server, node.js etc)
     nodejs 12.16.1 LTS

**Comment by z3dev** [comment]
@hrgdavor Super. And thanks for the quick feedback. :)

**Comment by hrgdavor** [comment]
I am using https://openjscad.org/ quite a lot lately, and have moved from OpenSCAD since OpenJSCAD i more live (development wise) ... and I love JS. So looking forward to your help fixing these initial steps, so I can test the V2 as early adopter.

**Comment by z3dev** [comment]
@hrgdavor this was fixed with pull request #529 

Can you try again? You probably need to run...
- git pull
- npm run clean
- npm run bootstrap

**Comment by hrgdavor** [comment]
did the steps, ... works ! :)
