### ISSUE TITLE
packages/desktop `npm run dev` not working #V2

### ISSUE THREAD

**Issue by hrgdavor** [jscad/OpenJSCAD.org#582]
## Expected Behavior
desktop app started

## Actual Behavior
error in console
```
Error: Cannot find module 'C:\wrk\OpenJSCAD.org\packages\desktop\node_modules\.bin\electron'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

## Steps to Reproduce the Problem

  1. get altest openjscad V2 branch
  2. npm install
  3. cd packages/desktop
  4 . npm run dev

## Specifications

  - Version: V2
  - Platform: Windows
  - Environment: nodejs 12.16.1

**Comment by skyl** [comment]
When I try to run the desktop on the v2 branch, I get

```
Uncaught Error: Cannot find module '@jscad/array-utils'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/Users/skyl/Code/OpenJSCAD.org/packages/desktop/node_modules/electron/dist/…ctron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/skyl/Code/OpenJSCAD.org/packages/desktop/src/sideEffects/fs.js:8:21)
    at Object.<anonymous> (/Users/skyl/Code/OpenJSCAD.org/packages/desktop/src/sideEffects/fs.js:139:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Comment by z3dev** [comment]
It hasn't been converted yet. Stay tuned...

**Comment by skyl** [comment]
sorry, I suppose mine is #543 , my bad

**Comment by ornamentist** [comment]
Do these 2020 installation instructions still apply in 2022?  I'm seeing the same error from a git clone of master/main.
