### ISSUE TITLE
V2 CLI

### ISSUE THREAD

**Issue by skyl** [jscad/OpenJSCAD.org#600]
## Expected Behavior

Can run cli.js in V2 branch

## Actual Behavior

```
$node cli.js ../examples/testV2.js -o foo.svg
```

```
JSCAD: generating output 
 from:  ../examples/testV2.js 
 to:  foo.svg (Scalable Vector Graphics Format) 

Error: Cannot find module '@jscad/modeling'
Require stack:
- /Users/skyl/Code/OpenJSCAD.org/packages/examples/testV2.js
- /Users/skyl/Code/OpenJSCAD.org/packages/core/code-evaluation/rebuildGeometryCli.js
- /Users/skyl/Code/OpenJSCAD.org/packages/cli/src/generateOutputData.js
- /Users/skyl/Code/OpenJSCAD.org/packages/cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/skyl/Code/OpenJSCAD.org/packages/examples/testV2.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/skyl/Code/OpenJSCAD.org/packages/examples/testV2.js',
    '/Users/skyl/Code/OpenJSCAD.org/packages/core/code-evaluation/rebuildGeometryCli.js',
    '/Users/skyl/Code/OpenJSCAD.org/packages/cli/src/generateOutputData.js',
    '/Users/skyl/Code/OpenJSCAD.org/packages/cli/cli.js'
  ]
}
```

## Steps to Reproduce the Problem

  1. clone, checkout V2 branch
  2. run `npm install`
  3. `cd packages/cli`
  4. `node cli.js ../examples/testV2.js`

## Specifications

  - Version: V2
  - Platform: osx node 12.18.0
  - Environment: node

**Comment by skyl** [comment]
oh sorry, #589
